### ISSUE TITLE
disorganized and duplicates 

### ISSUE THREAD

**Issue by bparkis167** [17FAFundDesktopSupport/equipment-Mgmt#3]
there are 2 5 whys documents and the procedure is labeled as the real scenario

**Comment by mmullins998** [comment]
I fixed it, the 2nd  5whys for later reference and unrelated to the assignment , the fishbone was incorrectly titled causing me to miss a file in the upload. As for the file named real_scenario.docx it is correctly named and relevant to the assignment.
